name: Security & Quality Scans

on:
  push:
    branches:
      - sonar3
  workflow_dispatch:
    inputs:
      branch:
        required: false
        
        default: "sonar3"

env:
  SONAR_PROJECT_KEY: cost-sense-ipredict
  SONAR_TOKEN: squ_f4b9c1214ac424228a22bdd05b8e96f174587807

jobs:
  sonarqube-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            -Dsonar.host.url=http://98.70.40.192:9025
            -Dsonar.login=${{ env.SONAR_TOKEN }}
            -Dsonar.sources=.
            -Dsonar.exclusions=**/sonarqube.py
      - name: Debug report-task.txt
        run: cat .scannerwork/report-task.txt

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: pip install requests pandas jinja2

      - name: Run SonarQube report generator
        run: python sonarqube.py
        env:
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
          SONAR_HOST_URL: http://98.70.40.192:9025
          SONAR_PROJECT_KEY: ${{ env.SONAR_PROJECT_KEY }}

      - name: Upload SonarQube Reports
        uses: actions/upload-artifact@v4
        with:
          name: sonarqube-reports
          path: sonarqube_output/**/*
