name: SonarQube Scan Test

on:
  workflow_dispatch:
    inputs:
      repositories:
        description: "Comma separated repo list (org/repo1,org/repo2)"
        required: true
      branch:
        description: "Branch to scan"
        required: false
        default: "main"

  schedule:
    - cron: "30 15 * * 5"   # Friday 9PM IST

  push:
    tags:
      - "v*"

env:
  SONAR_HOST_URL: http://98.70.40.192:9025

jobs:
  sonarqube-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout workflow repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install requests pandas jinja2
          
      - name: Parse repository list
        id: parse
        run: |
          echo "repos=${{ github.event.inputs.repositories }}" >> $GITHUB_OUTPUT
          
      - name: Install SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli-5.0.1.3006-linux.zip
          echo "$PWD/sonar-scanner-5.0.1.3006-linux/bin" >> $GITHUB_PATH

      - name: Loop through repositories
        env:
          REPOS: ${{ steps.parse.outputs.repos }}
          BRANCH: ${{ github.event.inputs.branch }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}
        run: |
          IFS=',' read -ra REPO_LIST <<< "$REPOS"

          for repo in "${REPO_LIST[@]}"
          do
            echo "Processing $repo"

            git clone https://x-access-token:${{ secrets.COSTSENSE_TOKEN }}@github.com/$repo.git
            repo_name=$(basename "$repo")

            cd $repo_name

            echo "Running SonarQube scan for $repo"

            sonar-scanner \
              -Dsonar.projectKey=$repo_name \
              -Dsonar.host.url=${{ env.SONAR_HOST_URL }} \
              -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
              -Dsonar.sources=. \
              -Dsonar.exclusions=**/sonarqube.py

            echo "Generating report for $repo_name"
  
            export SONAR_PROJECT_KEY=$repo_name
            export TARGET_REPO_URL=https://github.com/$repo
      
            python ../sonarqube.py

            cd ..

          done

      

      # - name: Run Sonar Report Script
      #   run: python sonarqube.py
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}

      - name: Upload Sonar Reports
        uses: actions/upload-artifact@v4
        with:
          name: sonarqube-report
          path: sonarqube_output/**/*

      - name: Generate Artifact Link
        id: artifact
        run: |
          echo "link=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_OUTPUT

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "SonarQube Scan Report"
          to: annalalal632@gmail.com
          from: GitHub Actions
          body: |
            SonarQube Scan Completed.

            Repositories: ${{ github.event.inputs.repositories }}

            Download Artifact:
            ${{ steps.artifact.outputs.link }}
